layout_spectrum: 0.1541219
color:
  saturation: 0.5
  lightness: 0
  brandStrength: 1
  brandColors:
    - '#000A00'
    - '#FFFFFF'
    - '#5EFFE6'
    - '#3DEB36'
    - '#FF4005'
  rhythmicContrast: 0.9614133
typography_spectrum: 0.188172
name: Willow Awards
